	window menu append submenu "stUser" "Network Analysis"
	window menu append item "Network Analysis" "Generate Network" "db nwgen"
	window menu append separator "Network Analysis"
	window menu append item "Network Analysis" "Open Networks" "run nwuse.do"
	window menu append item "Network Analysis" "Save Networks As..." "run nwsave.do"
	window menu append separator "Network Analysis"
	window menu append item "Network Analysis" "Import Networks" "db nwimport"
	window menu append item "Network Analysis" "Export Networks" "db nwexport"
	window menu append separator "Network Analysis"
	window menu append item "Network Analysis" "Example Networks" "help netexample"
	window menu append separator "Network Analysis"
	window menu append item "Network Analysis" "Summarize" "db nwsummarize"
	window menu append item "Network Analysis" "Node centrality" "db nwcentrality"
	window menu append separator "Network Analysis"
	window menu append item "Network Analysis" "Plot" "db nwplot"	
	window menu append item "Network Analysis" "Plot as matrix" "db nwplotmatrix"		
	window menu append item "Network Analysis" "Animate" "db nwsummarize"
	window menu append separator "Network Analysis"
	window menu refresh
